#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="deberes_4to")]
	public partial class MonolitoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_rol(tbl_rol instance);
    partial void Updatetbl_rol(tbl_rol instance);
    partial void Deletetbl_rol(tbl_rol instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    partial void Inserttbl_usuario_fotos(tbl_usuario_fotos instance);
    partial void Updatetbl_usuario_fotos(tbl_usuario_fotos instance);
    partial void Deletetbl_usuario_fotos(tbl_usuario_fotos instance);
    #endregion
		
		public MonolitoDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.deberes_4toConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_rol> tbl_rol
		{
			get
			{
				return this.GetTable<tbl_rol>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuario
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario_fotos> tbl_usuario_fotos
		{
			get
			{
				return this.GetTable<tbl_usuario_fotos>();
			}
		}
		
		public System.Data.Linq.Table<vw_EstadoCuentas> vw_EstadoCuentas
		{
			get
			{
				return this.GetTable<vw_EstadoCuentas>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ResetearIntentosCaducados")]
		public int sp_ResetearIntentosCaducados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_rol")]
	public partial class tbl_rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rol_id;
		
		private string _nombre_rol;
		
		private string _descripcion;
		
		private EntitySet<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onnombre_rolChanging(string value);
    partial void Onnombre_rolChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tbl_rol()
		{
			this._tbl_usuario = new EntitySet<tbl_usuario>(new Action<tbl_usuario>(this.attach_tbl_usuario), new Action<tbl_usuario>(this.detach_tbl_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_rol", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_rol
		{
			get
			{
				return this._nombre_rol;
			}
			set
			{
				if ((this._nombre_rol != value))
				{
					this.Onnombre_rolChanging(value);
					this.SendPropertyChanging();
					this._nombre_rol = value;
					this.SendPropertyChanged("nombre_rol");
					this.Onnombre_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_usuario", Storage="_tbl_usuario", ThisKey="rol_id", OtherKey="rol_id")]
		public EntitySet<tbl_usuario> tbl_usuario
		{
			get
			{
				return this._tbl_usuario;
			}
			set
			{
				this._tbl_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = this;
		}
		
		private void detach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_nombres;
		
		private string _usu_cedula;
		
		private string _correo_electronico;
		
		private string _contraseña;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private System.Nullable<int> _edad;
		
		private string _usu_nickname;
		
		private string _numero_celular;
		
		private string _codigo_otp;
		
		private System.Nullable<System.DateTime> _fecha_otp_generado;
		
		private int _intentos_fallidos;
		
		private int _rol_id;
		
		private System.DateTime _fecha_creacion;
		
		private bool _clave_temporal;
		
		private EntitySet<tbl_usuario_fotos> _tbl_usuario_fotos;
		
		private EntityRef<tbl_rol> _tbl_rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Oncorreo_electronicoChanging(string value);
    partial void Oncorreo_electronicoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void OnedadChanging(System.Nullable<int> value);
    partial void OnedadChanged();
    partial void Onusu_nicknameChanging(string value);
    partial void Onusu_nicknameChanged();
    partial void Onnumero_celularChanging(string value);
    partial void Onnumero_celularChanged();
    partial void Oncodigo_otpChanging(string value);
    partial void Oncodigo_otpChanged();
    partial void Onfecha_otp_generadoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_otp_generadoChanged();
    partial void Onintentos_fallidosChanging(int value);
    partial void Onintentos_fallidosChanged();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onfecha_creacionChanging(System.DateTime value);
    partial void Onfecha_creacionChanged();
    partial void Onclave_temporalChanging(bool value);
    partial void Onclave_temporalChanged();
    #endregion
		
		public tbl_usuario()
		{
			this._tbl_usuario_fotos = new EntitySet<tbl_usuario_fotos>(new Action<tbl_usuario_fotos>(this.attach_tbl_usuario_fotos), new Action<tbl_usuario_fotos>(this.detach_tbl_usuario_fotos));
			this._tbl_rol = default(EntityRef<tbl_rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(20)")]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this.Oncorreo_electronicoChanging(value);
					this.SendPropertyChanging();
					this._correo_electronico = value;
					this.SendPropertyChanged("correo_electronico");
					this.Oncorreo_electronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nickname", DbType="NVarChar(100)")]
		public string usu_nickname
		{
			get
			{
				return this._usu_nickname;
			}
			set
			{
				if ((this._usu_nickname != value))
				{
					this.Onusu_nicknameChanging(value);
					this.SendPropertyChanging();
					this._usu_nickname = value;
					this.SendPropertyChanged("usu_nickname");
					this.Onusu_nicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_celular", DbType="NVarChar(20)")]
		public string numero_celular
		{
			get
			{
				return this._numero_celular;
			}
			set
			{
				if ((this._numero_celular != value))
				{
					this.Onnumero_celularChanging(value);
					this.SendPropertyChanging();
					this._numero_celular = value;
					this.SendPropertyChanged("numero_celular");
					this.Onnumero_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_otp", DbType="NVarChar(10)")]
		public string codigo_otp
		{
			get
			{
				return this._codigo_otp;
			}
			set
			{
				if ((this._codigo_otp != value))
				{
					this.Oncodigo_otpChanging(value);
					this.SendPropertyChanging();
					this._codigo_otp = value;
					this.SendPropertyChanged("codigo_otp");
					this.Oncodigo_otpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_otp_generado", DbType="DateTime2")]
		public System.Nullable<System.DateTime> fecha_otp_generado
		{
			get
			{
				return this._fecha_otp_generado;
			}
			set
			{
				if ((this._fecha_otp_generado != value))
				{
					this.Onfecha_otp_generadoChanging(value);
					this.SendPropertyChanging();
					this._fecha_otp_generado = value;
					this.SendPropertyChanged("fecha_otp_generado");
					this.Onfecha_otp_generadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intentos_fallidos", DbType="Int NOT NULL")]
		public int intentos_fallidos
		{
			get
			{
				return this._intentos_fallidos;
			}
			set
			{
				if ((this._intentos_fallidos != value))
				{
					this.Onintentos_fallidosChanging(value);
					this.SendPropertyChanging();
					this._intentos_fallidos = value;
					this.SendPropertyChanged("intentos_fallidos");
					this.Onintentos_fallidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", DbType="Int NOT NULL")]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					if (this._tbl_rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime2 NOT NULL")]
		public System.DateTime fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this.Onfecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_creacion = value;
					this.SendPropertyChanged("fecha_creacion");
					this.Onfecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave_temporal", DbType="Bit NOT NULL")]
		public bool clave_temporal
		{
			get
			{
				return this._clave_temporal;
			}
			set
			{
				if ((this._clave_temporal != value))
				{
					this.Onclave_temporalChanging(value);
					this.SendPropertyChanging();
					this._clave_temporal = value;
					this.SendPropertyChanged("clave_temporal");
					this.Onclave_temporalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_fotos", Storage="_tbl_usuario_fotos", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_usuario_fotos> tbl_usuario_fotos
		{
			get
			{
				return this._tbl_usuario_fotos;
			}
			set
			{
				this._tbl_usuario_fotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_usuario", Storage="_tbl_rol", ThisKey="rol_id", OtherKey="rol_id", IsForeignKey=true)]
		public tbl_rol tbl_rol
		{
			get
			{
				return this._tbl_rol.Entity;
			}
			set
			{
				tbl_rol previousValue = this._tbl_rol.Entity;
				if (((previousValue != value) 
							|| (this._tbl_rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_rol.Entity = null;
						previousValue.tbl_usuario.Remove(this);
					}
					this._tbl_rol.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario.Add(this);
						this._rol_id = value.rol_id;
					}
					else
					{
						this._rol_id = default(int);
					}
					this.SendPropertyChanged("tbl_rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario_fotos(tbl_usuario_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_usuario_fotos(tbl_usuario_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario_fotos")]
	public partial class tbl_usuario_fotos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _foto_id;
		
		private int _usu_id;
		
		private string _nombre_archivo;
		
		private string _content_type;
		
		private System.Data.Linq.Binary _foto;
		
		private System.DateTime _fecha_subida;
		
		private bool _es_principal;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfoto_idChanging(int value);
    partial void Onfoto_idChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onnombre_archivoChanging(string value);
    partial void Onnombre_archivoChanged();
    partial void Oncontent_typeChanging(string value);
    partial void Oncontent_typeChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    partial void Onfecha_subidaChanging(System.DateTime value);
    partial void Onfecha_subidaChanged();
    partial void Ones_principalChanging(bool value);
    partial void Ones_principalChanged();
    #endregion
		
		public tbl_usuario_fotos()
		{
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int foto_id
		{
			get
			{
				return this._foto_id;
			}
			set
			{
				if ((this._foto_id != value))
				{
					this.Onfoto_idChanging(value);
					this.SendPropertyChanging();
					this._foto_id = value;
					this.SendPropertyChanged("foto_id");
					this.Onfoto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_archivo", DbType="NVarChar(255)")]
		public string nombre_archivo
		{
			get
			{
				return this._nombre_archivo;
			}
			set
			{
				if ((this._nombre_archivo != value))
				{
					this.Onnombre_archivoChanging(value);
					this.SendPropertyChanging();
					this._nombre_archivo = value;
					this.SendPropertyChanged("nombre_archivo");
					this.Onnombre_archivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_type", DbType="NVarChar(100)")]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this.Oncontent_typeChanging(value);
					this.SendPropertyChanging();
					this._content_type = value;
					this.SendPropertyChanged("content_type");
					this.Oncontent_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_subida", DbType="DateTime2 NOT NULL")]
		public System.DateTime fecha_subida
		{
			get
			{
				return this._fecha_subida;
			}
			set
			{
				if ((this._fecha_subida != value))
				{
					this.Onfecha_subidaChanging(value);
					this.SendPropertyChanging();
					this._fecha_subida = value;
					this.SendPropertyChanged("fecha_subida");
					this.Onfecha_subidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_es_principal", DbType="Bit NOT NULL")]
		public bool es_principal
		{
			get
			{
				return this._es_principal;
			}
			set
			{
				if ((this._es_principal != value))
				{
					this.Ones_principalChanging(value);
					this.SendPropertyChanging();
					this._es_principal = value;
					this.SendPropertyChanged("es_principal");
					this.Ones_principalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_fotos", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_usuario_fotos.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario_fotos.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_EstadoCuentas")]
	public partial class vw_EstadoCuentas
	{
		
		private int _usu_id;
		
		private string _usu_nombres;
		
		private string _usu_nickname;
		
		private string _correo_electronico;
		
		private int _intentos_fallidos;
		
		private string _estado_cuenta;
		
		private System.Nullable<System.DateTime> _ultimo_intento;
		
		private int _rol_id;
		
		public vw_EstadoCuentas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this._usu_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this._usu_nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nickname", DbType="NVarChar(100)")]
		public string usu_nickname
		{
			get
			{
				return this._usu_nickname;
			}
			set
			{
				if ((this._usu_nickname != value))
				{
					this._usu_nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this._correo_electronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intentos_fallidos", DbType="Int NOT NULL")]
		public int intentos_fallidos
		{
			get
			{
				return this._intentos_fallidos;
			}
			set
			{
				if ((this._intentos_fallidos != value))
				{
					this._intentos_fallidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_cuenta", DbType="VarChar(34) NOT NULL", CanBeNull=false)]
		public string estado_cuenta
		{
			get
			{
				return this._estado_cuenta;
			}
			set
			{
				if ((this._estado_cuenta != value))
				{
					this._estado_cuenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ultimo_intento", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ultimo_intento
		{
			get
			{
				return this._ultimo_intento;
			}
			set
			{
				if ((this._ultimo_intento != value))
				{
					this._ultimo_intento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", DbType="Int NOT NULL")]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this._rol_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
